# Generated by Django 4.0 on 2022-02-04 09:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_pic',
            field=models.ImageField(blank=True, default='users/admin.jpg', null=True, upload_to=main.models.saveDp),
        ),
    ]
