# Generated by Django 4.0 on 2022-03-22 15:13

from django.db import migrations, models
import main.helper


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='display_pic',
            field=models.ImageField(blank=True, default='businesses/shop.jpg', null=True, upload_to=main.helper.saveBDp),
        ),
        migrations.AlterField(
            model_name='businessimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.helper.saveBImg),
        ),
    ]
