# Generated by Django 4.0 on 2022-03-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_business_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default='This is a business', max_length=500),
            preserve_default=False,
        ),
    ]
