# Generated by Django 4.0 on 2022-03-23 12:22

from django.db import migrations, models
import main.helper


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='display_pic',
            field=models.ImageField(blank=True, default='businesses/shop.png', null=True, upload_to=main.helper.saveBDp),
        ),
    ]
