# Generated by Django 4.0 on 2022-03-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_businessimage_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='main.business'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated', to='main.user'),
        ),
    ]
